version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    restart: always
    networks:
      - ${NETWORK}
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${USER_RABBITMQ}   # Usuario definido
      RABBITMQ_DEFAULT_PASS: ${PASSWORD_RABBITMQ}  # Contraseña definida
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - ${NETWORK}
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_MYSQL_DOCKER}
      MYSQL_USER: paul
      MYSQL_PASSWORD: paulp
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ${NETWORK}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d

  gateway:
    container_name: gateway
    build:
      context: ./gateway
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MASIVOS_SERVICE_URL=${MASIVOS_SERVICE_URL}
      - GESTOR_SERVICE_URL=${GESTOR_SERVICE_URL}
      - LEADS_SERVICE_URL=${LEADS_SERVICE_URL}
      - STORAGE_SERVICE_URL=${STORAGE_SERVICE_URL}
      - USUARIOS_SERVICE_URL=${USUARIOS_SERVICE_URL}
      - MAILING_SERVICE_URL=${MAILING_SERVICE_URL}
    networks:
      - ${NETWORK}
    command: ["npm", "run", "dev"]
    develop:
      watch:
        - action: sync
          path: ./gateway
          target: /app
          ignore:
            - node_modules/

  masivos:
    container_name: masivos
    build:
      context: ./masivos
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DB_NAME=${DB_NAME_MASIVOS}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_DIALECT=${DB_DIALECT}
      - DB_PORT=${DB_PORT}
      - ALTER=${ALTER}
      - DB_HOST_MYSQL_DOCKER=${DB_HOST_MYSQL_DOCKER}
      - DB_USER_MYSQL_DOCKER=${DB_USER_MYSQL_DOCKER}
      - DB_PASSWORD_MYSQL_DOCKER=${DB_PASSWORD_MYSQL_DOCKER}
      - DOCKER_HOST_DEMON=${DOCKER_HOST_DEMON}
      - TIMEOUT_WEBSOCKET=${TIMEOUT_WEBSOCKET}
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=${GOOGLE_SERVICE_ACCOUNT_EMAIL}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY_R2=${SECRET_KEY_R2}
      - ENDPOINT_URL=${ENDPOINT_URL}
      - BUCKET_NAME=${BUCKET_NAME}
      - HOST_RABBITMQ=${HOST_RABBITMQ}
      - USER_RABBITMQ=${USER_RABBITMQ}
      - PASSWORD_RABBITMQ=${PASSWORD_RABBITMQ}
      - HOST_INTERNAL=${HOST_INTERNAL}
    depends_on:
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    volumes:
      - //./pipe/docker_engine:/var/run/docker.sock
    networks:
      - ${NETWORK}
    command: ["npm", "run", "dev"]
    develop:
      watch:
        - action: sync
          path: ./masivos
          target: /app
          ignore:
            - node_modules/

  gestor-archivos:
    container_name: gestor
    build:
      context: ./gestor-archivos
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - DB_NAME=${DB_NAME_GESTOR}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_DIALECT=${DB_DIALECT}
      - DB_PORT=${DB_PORT}
      - ALTER=${ALTER}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY_R2=${SECRET_KEY_R2}
      - ENDPOINT_URL=${ENDPOINT_URL}
      - BUCKET_NAME=${BUCKET_NAME}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ${NETWORK}
    command: ["npm", "run", "dev"]
    develop:
      watch:
        - action: sync
          path: ./gestor-archivos
          target: /app
          ignore:
            - node_modules/

  leads:
    container_name: leads
    build:
      context: ./leads
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
      - LOAD_DATA=false
      - DB_NAME=${DB_NAME_LEADS}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_DIALECT=${DB_DIALECT}
      - DB_PORT=${DB_PORT}
      - ALTER=${ALTER}
      - HOST_RABBITMQ=${HOST_RABBITMQ}
      - USER_RABBITMQ=${USER_RABBITMQ}
      - PASSWORD_RABBITMQ=${PASSWORD_RABBITMQ}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ${NETWORK}
    command: ["npm", "run", "dev"]
    develop:
      watch:
        - action: sync
          path: ./leads
          target: /app
          ignore:
            - node_modules/

  storage:
    container_name: storage
    build:
      context: ./storage
    ports:
      - "8004:8004"
    environment:
      - PORT=8004
      - DB_NAME=${DB_NAME_STORAGE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_DIALECT=${DB_DIALECT}
      - DB_PORT=${DB_PORT}
      - ALTER=${ALTER}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ${NETWORK}
    command: ["npm", "run", "dev"]
    develop:
      watch:
        - action: sync
          path: ./storage
          target: /app
          ignore:
            - node_modules/

  usuarios:
    container_name: usuarios
    build:
      context: ./usuarios
    ports:
      - "8005:8005"
    environment:
      - PORT=8005
      - DB_NAME=${DB_NAME_USUARIOS}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_DIALECT=${DB_DIALECT}
      - DB_PORT=${DB_PORT}
      - ALTER=${ALTER}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ${NETWORK}
    command: ["npm", "run", "dev"]
    develop:
      watch:
        - action: sync
          path: ./usuarios
          target: /app
          ignore:
            - node_modules/

  mailing:
    container_name: mailing
    build:
      context: ./mailing
    ports:
      - "8006:8006"
    environment:
      - PORT=8006
      - DB_NAME=${DB_NAME_MAILING}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_DIALECT=${DB_DIALECT}
      - DB_PORT=${DB_PORT}
      - ALTER=${ALTER}
      - HOST_RABBITMQ=${HOST_RABBITMQ}
      - USER_RABBITMQ=${USER_RABBITMQ}
      - PASSWORD_RABBITMQ=${PASSWORD_RABBITMQ}
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - ${NETWORK}
    command: ["npm", "run", "dev"]
    develop:
      watch:
        - action: sync
          path: ./mailing
          target: /app
          ignore:
            - node_modules/
  telebot:
    container_name: telebot
    build: 
      context: ./telebot
    ports:
      - "8007:8007"
    environment:
      - PORT=8007
      - DB_NAME=${DB_NAME_TELEBOT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - HOST_RABBITMQ=${HOST_RABBITMQ}
      - USER_RABBITMQ=${USER_RABBITMQ}
      - PASSWORD_RABBITMQ=${PASSWORD_RABBITMQ}
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - ${NETWORK}
    command: ["python", "src/App.py"]
    develop:
      watch:
        - action: sync
          path: ./telebot
          target: /app
volumes:
  mysql_data:

networks:
  bot-network:
    external: true
