# Usa una imagen base de Python 3.10
FROM python:3.10

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de requerimientos e instala dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo el código fuente al contenedor
COPY . .

# Expone el puerto si la aplicación lo necesita (ajusta si es necesario)
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["python", "src/app.py"]
